#!/usr/bin/env bash
# Regenerates Probe/SampleContext.swift (Docs/19 M0) from the vendored Starlette analysis:
# the same kinds of text ContextBuilder feeds the model (components, claims, a code_graph.json
# slice), so the probe's chars-per-token and throughput numbers reflect real Orion prompts.
# The sample is a string literal, not a bundle resource, so the macOS `fm-probe` tool (which
# has no bundle) and the iOS app share it.
set -euo pipefail
here="$(cd "$(dirname "$0")/.." && pwd)"
orion="${ORION_SAMPLE_DIR:-$here/../Agent Feasibility Study/vendor/starlette/.orion}"
db="$orion/orion.db"
out="$here/Probe/SampleContext.swift"

components=$(sqlite3 "$db" "select '- ' || name || ' (' || coalesce(architectural_role,'') || '): ' || coalesce(description,'') from components order by name;")
claims=$(sqlite3 "$db" "select '- [' || claim_type || '] ' || statement from claims where statement not like '%\"\"\"%' order by id limit 60;")
graph=$(head -c 6000 "$orion/export/code_graph.json")

{
  echo "// Generated by scripts/make-sample-context.sh -- do not edit by hand."
  echo "// Source: vendored Starlette 1.6.0 analysis (orion.db + export/code_graph.json)."
  echo "enum SampleContext {"
  echo "    static let text = #\"\"\""
  echo "## Components"
  echo "$components"
  echo
  echo "## Claims"
  echo "$claims"
  echo
  echo "## Code graph (excerpt)"
  echo "$graph"
  echo "\"\"\"#"
  echo "}"
} > "$out"
echo "wrote $out ($(wc -c < "$out") bytes)"
