// Generated by scripts/make-sample-context.sh -- do not edit by hand.
// Source: vendored Starlette 1.6.0 analysis (orion.db + export/code_graph.json).
enum SampleContext {
    static let text = #"""
## Components
- Application & ASGI Core (core): The top-level Starlette application object and the shared ASGI type vocabulary (Scope/Receive/Send/ASGIApp/Lifespan). Starlette wires a Router together with a lazily-built middleware stack and dispatches every incoming ASGI connection through it.
- Application & Middleware Assembly (core): The public entrypoint: the Starlette class holds routes, user middleware, exception handlers and lifespan, and lazily assembles them (plus fixed error/exception bookends) into a single ASGI callable. Middleware is a lightweight (class, args, kwargs) descriptor used to build that stack.
- Application Core & ASGI Assembly (core): The top-level Starlette application object and the Middleware wrapper it uses to lazily assemble a layered ASGI callable around the router.
- Authentication (supporting): Pluggable authentication: an AuthenticationBackend contract, credential/user model classes, the @requires route decorator, and AuthenticationMiddleware that populates request.auth / request.user from a backend.
- Authentication & Sessions (supporting): Identity and session concerns: pluggable authentication backends with user/credential models and the @requires decorator, the middleware that runs a backend and populates request.user/auth, and cookie-backed session middleware.
- Authentication Framework (supporting): Pluggable auth primitives: an AuthenticationBackend contract, credential/user model classes, and the requires decorator that enforces scopes on endpoints. Wired into requests via AuthenticationMiddleware, which populates conn.auth / conn.user.
- Built-in ASGI Middleware (supporting): Optional pure-ASGI wrappers the user adds to the stack: CORS, GZip, sessions, trusted-host, HTTPS redirect, request body-size limiting, WSGI bridging, authentication, and the BaseHTTPMiddleware bridge that lets middleware be written as request->response dispatch functions.
- Concurrency, Utilities & Configuration (supporting): Low-level helpers used throughout: threadpool/async adapters and task-group utilities, async-callable and route-path helpers, and an environment/.env-backed Config loader with type casting.
- Data Structures (supporting): Immutable/mutable container and value types shared across the framework: URL/URLPath, Headers/MutableHeaders, QueryParams and the MultiDict family, FormData/UploadFile, Secret, State, Address, CommaSeparatedStrings.
- Data Structures & Concurrency Utilities (supporting): Shared value types (URL, Headers/MutableHeaders, MultiDict family, QueryParams, UploadFile, FormData, State, Secret, Address) plus low-level helpers for threadpool offloading, async-callable detection, route-path extraction, and environment-driven configuration.
- Exception Handling (core): Cross-cutting error handling: HTTPException/WebSocketException types, the handler-lookup/wrapping helper, ServerErrorMiddleware (catches unhandled 500s, renders debug pages) and ExceptionMiddleware (maps exceptions and status codes to registered handlers), plus HTTP/WS status-code constants.
- Exception Handling (supporting): The framework's error model: HTTPException/WebSocketException types, the shared handler-lookup and app-wrapping helper used by both routing and ExceptionMiddleware, and the HTTP/WebSocket status-code constants.
- Exception Handling (core): Turns exceptions into responses at two layers: per-endpoint/ExceptionMiddleware handling of HTTPException and registered handlers (by status code or exception class via MRO lookup), and an outermost ServerErrorMiddleware catch-all that renders 500s (with a debug traceback page).
- Form Parsing (supporting): Streaming parsers for request bodies: urlencoded form parsing and multipart/form-data parsing (with spooled file uploads and size limits), used by Request.form().
- Foundational Utilities & ASGI Contracts (foundational): Framework-wide primitives with no internal dependencies of their own: ASGI type aliases, HTTP/WS status constants, threadpool/async concurrency helpers, small async utilities (is_async_callable, get_route_path), and the environment-backed Config loader.
- HTTP Data Structures & Form Parsing (supporting): Reusable value types shared across the framework (URL, URLPath, immutable/mutable Headers, QueryParams, MultiDict, FormData, UploadFile, State, Address, Secret) plus the urlencoded and streaming multipart form parsers consumed by Request.form().
- Middleware Stack (core): The Middleware wrapper/factory plus the built-in ASGI middleware set (CORS, GZip, sessions, trusted-host, HTTPS redirect, request body limit, WSGI bridge) and BaseHTTPMiddleware, which adapts the ASGI protocol into a request-to-response dispatch callback.
- Middleware Suite (core): The stack of pluggable ASGI middleware: the request/response-style BaseHTTPMiddleware bridge plus concrete middlewares for server errors, CORS, GZip, HTTPS redirect, trusted hosts, body-size limits, and WSGI interop.
- Request & WebSocket Connections (core): The inbound half of the request/response cycle: HTTPConnection and its Request subclass expose the ASGI scope as headers, query params, cookies, body/stream/json/form accessors, plus the WebSocket connection object and its disconnect/close signals.
- Requests & WebSockets (core): Inbound-side abstractions over the ASGI scope/receive channel: HTTPConnection and Request expose headers, query params, cookies, body/stream/json/form access and disconnection detection; WebSocket wraps the bidirectional websocket protocol and its state machine.
- Requests, WebSockets & Form Parsing (core): Read-side view over the ASGI connection: HTTPConnection and its Request/WebSocket subclasses expose lazily-parsed scope data and the incoming body, and the streaming form parsers turn request bodies into FormData.
- Responses & Background Tasks (core): Outbound-side abstractions: Response and its subtypes (HTML/PlainText/JSON/Redirect/Streaming/File) are themselves ASGI apps that emit response.start/body messages, handle cookies and byte-range requests, and run attached background tasks after the body is sent.
- Responses & Background Tasks (core): The outbound half: a Response base that renders bytes and emits ASGI send messages, plus specialized subclasses (HTML, plain text, JSON, redirect, streaming, file with range support) and background task objects run after the response is sent.
- Responses, Background Tasks & Templating (core): Write-side of the framework: Response and its subclasses (plain/HTML/JSON/redirect/streaming/file) are ASGI apps that emit start+body messages, BackgroundTask(s) run after the response is sent, and Jinja2Templates renders template responses.
- Routing & Endpoint Dispatch (core): Matches incoming ASGI scopes to routes and hands off to handlers. Contains the route tree (Route, WebSocketRoute, Mount, Host), the Router (also owner of lifespan), path-to-regex compilation with typed convertors, the function-to-ASGI adapters, and the class-based endpoint bases.
- Routing & Endpoints (core): Path/host matching and dispatch: compiles path templates into regexes using pluggable convertors, matches requests to Route/WebSocketRoute/Mount/Host, adapts handler functions into ASGI apps, and manages application lifespan. Also includes the class-based HTTP/WebSocket endpoint style.
- Routing & Endpoints (core): URL path compilation, route matching (HTTP routes, websocket routes, sub-app mounts, host routing), the Router that dispatches ASGI calls and drives lifespan, and the class-based endpoint handlers. Includes the path-parameter convertor system.
- Serving Helpers (Static Files, Templating, Schemas) (supporting): Optional higher-level building blocks mounted as endpoints: a StaticFiles ASGI app with conditional/not-modified handling, Jinja2Templates producing streaming TemplateResponses, and an OpenAPI schema generator that introspects routes.
- Static Files & API Schema Generation (supporting): Two standalone, mountable capabilities: the StaticFiles ASGI app that serves files from disk with caching/range support, and the SchemaGenerator that builds an OpenAPI document from route docstrings.
- Static Files, Templating & Schemas (supporting): Higher-level feature helpers built on Responses/Routing: a StaticFiles ASGI app with caching/304 handling, a Jinja2Templates wrapper producing TemplateResponse, and an OpenAPI schema generator that introspects the route table.
- Test Client (supporting): An in-process test harness that drives the ASGI app through an httpx transport, using an AnyIO portal to bridge sync test code to the async app and providing a synchronous WebSocket test session.
- Test Client (supporting): In-process testing harness: a requests/httpx-style client that drives the ASGI app via a custom transport, plus a synchronous WebSocket test session and lifespan management.
- Test Client (supporting): An in-process test harness that drives the ASGI app through httpx using a custom transport and an anyio portal, with a synchronous WebSocket test session and lifespan startup/shutdown control.

## Claims
- [INTERPRETATION] Responses are themselves ASGI applications: Response.__call__ emits the http.response.start and body messages and then invokes any attached BackgroundTask/BackgroundTasks after the response body has been sent.
- [INTERPRETATION] The CORSMiddleware in Starlette short-circuits CORS preflight requests by checking for the `OPTIONS` method and specific CORS headers (e.g., `Access-Control-Request-Method`, `Access-Control-Request-Headers`) in the `__call__` method. If a preflight request is detected, it generates a response with the appropriate CORS headers (e.g., `Access-Control-Allow-Methods`, `Access-Control-Allow-Headers`, `Access-Control-Max-Age`) via the `preflight_response` method and returns it immediately. This bypasses the routing layer, ensuring preflight requests are handled without invoking route handlers, adhering to CORS protocol standards.
- [INTERPRETATION] ExceptionMiddleware in Starlette is responsible for handling uncaught exceptions in ASGI applications. By default, it handles HTTPException (from starlette/exceptions.py) and WebSocketException (from starlette/exceptions.py) by converting them into appropriate HTTP responses or closing WebSocket connections. It does this through its http_exception and websocket_exception methods.
- [INTERPRETATION] request_response and websocket_session are adapters that wrap an ordinary handler function into an ASGI callable, constructing a Request/WebSocket from the scope and running the call inside wrap_app_handling_exceptions so handler errors are routed to the exception-handling layer.
- [UNKNOWN] The exact ordering/precedence semantics of ExceptionMiddleware's status-code handlers vs. exception-class handlers (starlette/middleware/exceptions.py) was not read in detail; the claim about handler lookup is inferred from module structure.
- [INTERPRETATION] Route matching is regex-based: compile_path turns a path template like '/users/{id:int}' into a compiled pattern plus a map of per-parameter Convertor objects at construction time, and Route.matches runs that pattern against the scope path and converts captured values.
- [UNKNOWN] Whether GZipMiddleware/IdentityResponder offload compression to a threadpool with a capacity limiter (symbols _gzip_capacity_limiter, _get_gzip_capacity_limiter suggest so) was not confirmed by reading the code.
- [CONTRADICTED] Starlette defers building its ASGI pipeline until the first call: Starlette.__call__ lazily invokes build_middleware_stack, which nests ServerErrorMiddleware as the outermost layer and ExceptionMiddleware as the innermost layer, with user middleware in between, all wrapping the Router.
- [INTERPRETATION] A class-based HTTPEndpoint is invoked by a Route through Starlette's routing system. When a Route is added via `Starlette.add_route()`, it maps a URL path to an HTTPEndpoint instance. When a request matches the route, Starlette's `__call__` method triggers the HTTPEndpoint's `dispatch` method. This method inspects the HTTP method (e.g., GET, POST) and calls the corresponding handler method (e.g., `get`, `post`) on the endpoint instance. If no handler matches, `method_not_allowed` is raised. The Route's handler is bound to the endpoint class, enabling the framework to invoke the correct method based on the request.
- [CONTRADICTED] The Router doubles as the lifespan manager: its __call__ dispatches 'lifespan' scopes to an async context manager (defaulting to _DefaultLifespan) for startup/shutdown, separate from its 'http' and 'websocket' route matching.
- [CONTRADICTED] Authentication in Starlette is handled via the `AuthenticationBackend` class, which defines an `authenticate` method. This method checks request credentials (via `AuthCredentials`) and returns a `BaseUser` object (e.g., `SimpleUser` or `UnauthenticatedUser`). Key steps:

1. **Authentication Backend**: `AuthenticationBackend.authenticate()` is called during request processing. It verifies credentials (e.g., from headers, tokens) and creates a user.

2. **User State**: `BaseUser` represents the authenticated user, with properties like `is_authenticated` (bool) and `identity` (user identifier). `UnauthenticatedUser` is used when no valid credentials are found.

3. **Protected Routes**: The `@requires()` decorator (from `starlette/authentication.py`) enforces authentication by checking if the user's `is_authenticated` is True before allowing access.

4. **Error Handling**: If authentication fails, `AuthenticationError` is raised, which typically results in an `HTTPException` (401/403).
- [UNKNOWN] How path_params captured by Mount/Route matching are merged and passed down into nested routers and endpoints (precedence when names collide, root_path vs path handling) is inferred from method names, not confirmed against the implementation.
- [CONTRADICTED] The value set in a ContextVar within a BaseHTTPMiddleware's dispatch() is visible only to code that executes **after** the middleware in the same request's context (e.g., subsequent middlewares or the application code). It is **not visible to code running outside/above the middleware** (earlier in the stack) or to subsequent requests. This is because ContextVars are bound to the current context (e.g., a request), and each request has its own isolated context. Thus, the value is scoped to the same request's execution chain, not shared across requests or earlier middleware.
- [INTERPRETATION] __eq__ treats two Routers as equal iff other is a Router and their routes lists are equal.
- [INTERPRETATION] The claim is supported by the following evidence:

1. **Definition**: `ServerErrorMiddleware` is defined in `starlette/middleware/errors.py` as a class with methods for handling server errors (e.g., `__call__`, `error_response`). This confirms it is a middleware component.

2. **Usage in Starlette**: The `Starlette` class in `starlette/applications.py` has an `add_middleware` method that appends middleware to the stack. While the code graph does not explicitly show `ServerErrorMiddleware` being added, the `import_alias` in `starlette/applications.py` indicates it is referenced there, suggesting it is included in the middleware stack by default.

3. **Tests**: Tests in the repository (e.g., `tests/middleware/test_server_error.py`) explicitly configure `ServerErrorMiddleware` as the outermost layer. For example, tests may use `app.add_middleware(ServerErrorMiddleware)` before other middleware, ensuring it is the first to process requests. This aligns with the claim that it is always the outermost layer.

**Source**: The `ServerErrorMiddleware` class and its integration with `Starlette` are explicitly documented in the codebase, and tests confirm its placement in the middleware stack.
- [CONTRADICTED] app() asserts scope['type'] is http/websocket/lifespan, sets scope['router']=self if absent, delegates lifespan scopes to self.lifespan(), then iterates self.routes calling route.matches(scope); a Match.FULL updates the scope and calls route.handle() and returns.
- [INTERPRETATION] AuthenticationMiddleware runs a pluggable AuthenticationBackend.authenticate on each connection and injects the resulting AuthCredentials and user into the scope, which HTTPConnection.auth / HTTPConnection.user then expose to endpoints and the @requires decorator.
- [INTERPRETATION] Changing `Request.__init__` to require a non-empty, always-callable receive channel would break code relying on the default stub. Key areas needing updates include:

1. **Starlette's ASGI lifecycle** (`starlette/applications.py::Starlette.__call__`) where requests are initialized.
2. **Benchmarking code** (`benchmarks/routing_benchmark.py::ASGIRunner`) using `Request` without a custom receive channel.
3. **WebSocket/HTTP endpoints** (`starlette/endpoints.py::HTTPEndpoint`, `starlette/endpoints.py::WebSocketEndpoint`) handling request bodies.
4. **Middleware** (`starlette/middleware/base.py::_CachedRequest`) caching request data.

All these areas must ensure `Request` is initialized with a valid receive channel.
- [INTERPRETATION] The documentation's note about contextvar propagation limitations is not contradicted by the code in 'middleware/base.py', as the file does not exist. The mentioned limitation remains the primary documented constraint for BaseHTTPMiddleware.
- [CONTRADICTED] TestClient runs the real ASGI application in-process by mounting a custom httpx transport that translates each HTTP call into an ASGI scope/receive/send exchange, bridging sync test code to the async app through an anyio portal and exposing WebSockets as a blocking WebSocketTestSession.
- [INTERPRETATION] AuthenticationMiddleware runs an AuthenticationBackend on each connection and exposes the result as request.auth (AuthCredentials) and request.user, which the @requires decorator then checks for required scopes before invoking the handler.
- [CONTRADICTED] The `BackgroundTasks.__call__` method allows adding tasks to the background queue by invoking `add_task`. Synchronous tasks are executed in a thread pool via `run_in_threadpool`, while asynchronous tasks are run directly using `asyncio`. This enables mixed execution of sync/async tasks within the same `BackgroundTasks` instance.
- [CONTRADICTED] The Test Client in this codebase provides an in-process ASGI application testing harness. It uses httpx with a custom `_TestClientTransport` to translate HTTP requests into ASGI scope/receive/send exchanges, enabling synchronous test code to interact with async ASGI applications. It also supports WebSocket testing through `WebSocketTestSession`, allowing blocking WebSocket interactions while managing async lifecycle via anyio portal.
- [INTERPRETATION] The Router class is defined in starlette/routing.py. Its app method (implemented as the __call__ method) handles incoming requests by routing them to the appropriate endpoints based on the registered routes.
- [UNKNOWN] There is an import cycle between starlette.requests, starlette.routing and starlette.applications (requests.py imports both routing and applications, routing imports requests). The component graph flattens this into 'Request & WebSocket Connections depends_on Routing & Endpoint Dispatch'; the real resolution likely relies on TYPE_CHECKING / deferred imports which was not verified line-by-line.
- [INTERPRETATION] The evidence is in the `BackgroundTasks.__call__` method, which is invoked after the response is finalized. In Starlette, background tasks are executed after the response body is sent, as the `__call__` method of `BackgroundTasks` is triggered during the response cleanup phase. This is corroborated by the `ResponsivenessBenchmark` in `benchmarks/gzip_benchmark.py`, which tests that tasks run post-response, ensuring no overlap with response generation.
- [CONTRADICTED] Starlette.build_middleware_stack() constructs the middleware stack by combining default middleware with user-added middleware. The middleware layers are applied in the order they were added via add_middleware(), with the first middleware in the list processing requests first. This ensures the request passes through each middleware in sequence, with the outermost (first-added) middleware handling the request first.
- [INFERENCE] app() captures the first Match.PARTIAL route and dispatches to it only when no full match is found, which is the mechanism the comment attributes to handling 405 Method Not Allowed.
- [CONTRADICTED] TestClient executes the ASGI app in-process by subclassing an httpx transport: _TestClientTransport.handle_request translates each httpx request into an ASGI scope with receive/send channels, so tests exercise the real middleware and routing stack without a network server.
- [CONTRADICTED] ASGI lifespan is handled entirely inside the Router rather than by middleware: Router.app short-circuits scope['type'] == 'lifespan' to Router.lifespan, which enters the lifespan context manager, optionally merges returned state into scope['state'], and emits startup/shutdown complete/failed messages.
- [CONTRADICTED] The Starlette documentation does not explicitly warn about exceptions raised in middleware bypassing ExceptionMiddleware or registered handlers. The implementation behavior depends on the middleware stack configuration: if the ExceptionMiddleware is included, it will handle exceptions raised during request processing, including those in middleware. However, the documentation does not explicitly address this scenario.
- [INTERPRETATION] Request.form dispatches on the Content-Type: multipart bodies are handled by MultiPartParser (producing UploadFile entries backed by a spooled temp file) and urlencoded bodies by FormParser, both returning a FormData mapping.
- [INTERPRETATION] The ASGI data flow begins when the server invokes `Starlette.__call__` with the scope, receive, and send functions. The Starlette app processes the scope to route the request to an endpoint (e.g., `HTTPEndpoint.dispatch`). The endpoint uses `receive()` to read the request body, processes it, and generates a response via `send()` (e.g., sending HTTP headers and body). The `send` function forwards the response back to the client through the ASGI server, completing the cycle.
- [INTERPRETATION] The codebase does not contain a symbol named 'ServerErrorMiddleware'. However, in Starlette, when an exception occurs within an application, the framework's middleware (such as `ExceptionMiddleware`) typically catches the exception and returns a 500 Internal Server Error response. In debug mode (`debug=True`), detailed error information (including tracebacks) is usually exposed to the client, while in non-debug mode (`debug=False`), error details are logged internally and a generic 500 response is returned to the client for security reasons.
- [UNKNOWN] The distinction between starlette.config (a standalone settings loader) and the rest of the framework: it is imported only by tests, so its architectural coupling to the running application is effectively zero despite being a public module.
- [INTERPRETATION] Routing turns path templates into regular expressions via compile_path using the registered Convertor types, and Route.matches reports a NONE/PARTIAL/FULL result while extracting typed path parameters into the scope.
- [INTERPRETATION] Starlette.add_middleware is intended to add middleware during application initialization, while build_middleware_stack constructs the middleware stack during app setup. If add_middleware is called after the application has started serving, a RuntimeError is raised because the middleware stack is finalized during initialization and cannot be modified afterward. This prevents inconsistent states and ensures middleware is properly configured before the app begins handling requests.
- [UNKNOWN] This answer recalls a string emitted in my previous turn's response; it is not derived from any repository symbol, so no anchor evidence applies.
- [INTERPRETATION] Path matching is precompiled: compile_path converts a route pattern like '/{id:int}' into a named-group regex plus a reversible format string and a per-parameter Convertor map, and Route.matches runs convertor.convert() on the captured strings to produce typed path_params; new converters can be registered globally via register_url_convertor.
- [CONTRADICTED] __call__ is the documented main entry point and merely awaits self.middleware_stack(scope, receive, send), so all routing work happens in app().
- [CONTRADICTED] In Starlette, ASGI contracts are implemented via the `Starlette` class in `applications.py`, which adheres to the ASGI protocol by defining methods like `__call__` to handle requests. The `ASGIRunner` classes in benchmarks (e.g., `benchmarks/gzip_benchmark.py`) simulate ASGI servers, using `run`, `close`, and `receive/send` methods to test how Starlette processes requests. This ensures compatibility with ASGI servers like Uvicorn, where the contract dictates how apps and servers exchange data via `scope`, `receive`, and `send`.
- [CONTRADICTED] Changing BackgroundTasks to run concurrently could break existing applications relying on sequential execution order, shared state consistency, or specific error handling. For example, tasks that depend on prior task outputs, shared resources without synchronization, or assume single-threaded execution might fail or produce incorrect results.
- [INFERENCE] Request.form() selects a parser by content type, delegating to MultiPartParser for multipart/form-data (with spooled UploadFile handling) and to FormParser for urlencoded bodies, caching the parsed FormData on the request.
- [INTERPRETATION] The endpoint's HTTPException(404) is handled by Starlette's framework, resulting in a clean 404 (4xx) response. The plain-ASGI middleware's HTTPException(400) is not handled by Starlette's exception system, leading to a 500 Internal Server Error. This is because ASGI middlewares operate at a lower level and do not integrate with Starlette's HTTPException handling mechanism.
- [CONTRADICTED] Router is a plain class whose primary state is self.routes, a list built from the routes argument (empty list when None), plus flags redirect_slashes and a default fallback app that defaults to self.not_found.
- [CONTRADICTED] The `BenchmarkCase` class in `benchmarks/gzip_benchmark.py` defines test cases for gzip-related benchmarks. It includes parameters like `size` (payload size), `payload_kind` (type of data), and `level` (compression level). These cases likely drive performance tests for gzip compression/decompression. To execute these tests, look for a test runner in the `benchmarks` directory or check if the codebase uses a testing framework like `pytest` or `unittest` to discover and run them.
- [INTERPRETATION] The claim is supported by the following evidence:

1. **Code Logic**: The `HTTPEndpoint.method_not_allowed` method in `starlette/endpoints.py` explicitly handles cases where a request's HTTP method is not allowed for a matched route. This method is designed to raise an `HTTPException` with status code 405 (`HTTP_405_METHOD_NOT_ALLOWED` from `starlette/status.py`), which corresponds to the 'Method Not Allowed' response.

2. **Test Case**: The `benchmarks/routing_benchmark.py::test_routing_method_not_allowed` function in the benchmarks explicitly tests this scenario. It simulates a request with a matching path but an incorrect HTTP method, expecting a 405 response with an 'Allow' header listing permitted methods.

3. **Header Handling**: The `HTTPException` constructor in `starlette/exceptions.py` allows setting the 'Allow' header, which is populated based on the endpoint's allowed methods. This ensures the response includes the required header when a method is not allowed.

These elements collectively confirm that a partial route match (path matches, method does not) results in a 405 response with an 'Allow' header, as claimed.
- [INTERPRETATION] request_response and websocket_session adapt a plain handler function into an ASGI application and wrap its execution in wrap_app_handling_exceptions, so exceptions raised inside endpoints are caught and routed to registered exception handlers rather than propagating raw.
- [INTERPRETATION] __init__ constructs self.middleware_stack starting from self.app, wrapping each Middleware from the middleware sequence in reversed order, and finally wrapping with RequestBodyLimitMiddleware when max_body_size is not None.
- [INTERPRETATION] If `build_middleware_stack` were changed to place `ExceptionMiddleware` outside user middleware, application authors would need to ensure their middleware does not raise unhandled exceptions, as `ExceptionMiddleware` would catch them. Previously, if `ExceptionMiddleware` was inside user middleware, it would not handle exceptions raised in the user's middleware. This change would require authors to adjust their middleware ordering or exception handling logic to avoid unintended suppression of errors.
- [UNKNOWN] starlette/config.py (Config/Environ) has no importers within the library (only tests) so its role as a first-class architectural component vs. an optional helper is ambiguous.
- [CONTRADICTED] The Starlette application is a thin coordinator: it holds configuration and lazily builds a single ASGI 'middleware onion' on the first request, always placing ServerErrorMiddleware as the outermost layer and ExceptionMiddleware as the innermost layer around the user's middleware and the Router.
- [CONTRADICTED] The TestClient in Starlette manages the application's lifespan only when used as a context manager because it implements the context manager protocol via `__enter__` and `__exit__` methods. These methods handle the application's startup and shutdown, ensuring lifespan events (e.g., `startup` and `shutdown`) are triggered. This behavior is enforced by the `AbstractContextManager` import from `contextlib`, which the TestClient leverages. Tests using `with TestClient(...)` explicitly tie the lifespan to the context manager's scope, while using it without `with` bypasses this management. Source: `starlette/testclient.py` (context manager implementation) and associated tests.
- [CONTRADICTED] When the ASGI app's lifespan context manager raises RuntimeError during startup (before yield), the ASGI server will fail to initialize the app, preventing request handling. Under TestClient, the same exception is raised during client setup, failing the test. Both cases propagate the RuntimeError from the lifespan's __aenter__ phase.
- [CONTRADICTED] TestClient exercises the application without a real server by routing httpx requests through an in-memory _TestClientTransport and using an AnyIO portal to call the async ASGI app from synchronous test code, with WebSocketTestSession providing a blocking websocket API.
- [INTERPRETATION] wrap_app_handling_exceptions tracks whether the ASGI response has already started and raises 'Caught handled exception, but response already started.' rather than attempting to send a second response, so exception-to-response conversion only works before the first http.response.start.
- [INTERPRETATION] When a DELETE request matches a GET-only route in Starlette:

1. **Status Code**: 405 Method Not Allowed (HTTP_405_METHOD_NOT_ALLOWED)
2. **Headers**: `Allow: GET`
3. **Code Path**:
   - Request reaches `HTTPEndpoint.dispatch`
   - Method mismatch triggers `HTTPEndpoint.method_not_allowed`
   - Generates response with 405 status and Allow header

This follows from the `method_not_allowed` implementation in `starlette/endpoints.py` and the HTTP status constants in `starlette/status.py`.
- [CONTRADICTED] Request dispatch is a linear scan: Router.app iterates its routes calling matches(scope), immediately handles the first FULL match, otherwise remembers the first PARTIAL match to raise 405 Method Not Allowed, and only then falls back to redirect-slash handling and the not-found handler.
- [CONTRADICTED] Routes, mounts and the Router are themselves standalone ASGI apps, making the system uniformly composable: BaseRoute.__call__ lets a single route run in isolation, Mount/Host carry sub-applications, and request_response/websocket_session adapt plain handler callables into the same ASGI interface.
- [CONTRADICTED] In Starlette, `Request.body()` reads the entire request body as a string once, and subsequent calls return an empty string because the stream is exhausted. `Request.stream()` provides an iterator that allows reading the body incrementally or multiple times, as it maintains the stream state. This distinction ensures `body()` is a one-time read, while `stream()` supports repeated access to the raw data.

## Code graph (excerpt)
{
  "classes" : [
    {
      "anchor" : "benchmarks/gzip_benchmark.py::ASGIRunner",
      "bases" : [

      ],
      "methods" : [
        "benchmarks/gzip_benchmark.py::ASGIRunner.__init__",
        "benchmarks/gzip_benchmark.py::ASGIRunner.run",
        "benchmarks/gzip_benchmark.py::ASGIRunner.close"
      ]
    },
    {
      "anchor" : "benchmarks/gzip_benchmark.py::BenchmarkCase",
      "bases" : [

      ],
      "methods" : [
        "benchmarks/gzip_benchmark.py::BenchmarkCase.id"
      ]
    },
    {
      "anchor" : "benchmarks/gzip_benchmark.py::BypassCase",
      "bases" : [

      ],
      "methods" : [

      ]
    },
    {
      "anchor" : "benchmarks/gzip_benchmark.py::ResponsePair",
      "bases" : [

      ],
      "methods" : [
        "benchmarks/gzip_benchmark.py::ResponsePair.warm_worker",
        "benchmarks/gzip_benchmark.py::ResponsePair.run_until_tiny_response",
        "benchmarks/gzip_benchmark.py::ResponsePair._run_until_tiny_response",
        "benchmarks/gzip_benchmark.py::ResponsePair.drain_and_validate",
        "benchmarks/gzip_benchmark.py::ResponsePair._drain_and_validate"
      ]
    },
    {
      "anchor" : "benchmarks/gzip_benchmark.py::ResponsivenessBenchmark",
      "bases" : [

      ],
      "methods" : [
        "benchmarks/gzip_benchmark.py::ResponsivenessBenchmark.__init__",
        "benchmarks/gzip_benchmark.py::ResponsivenessBenchmark.setup",
        "benchmarks/gzip_benchmark.py::ResponsivenessBenchmark.run_until_tiny_response",
        "benchmarks/gzip_benchmark.py::ResponsivenessBenchmark.teardown"
      ]
    },
    {
      "anchor" : "benchmarks/gzip_benchmark.py::StaticResponseApp",
      "bases" : [

      ],
      "methods" : [
        "benchmarks/gzip_benchmark.py::StaticResponseApp.__init__",
        "benchmarks/gzip_benchmark.py::StaticResponseApp.__call__"
      ]
    },
    {
      "anchor" : "benchmarks/routing_benchmark.py::ASGIRunner",
      "bases" : [

      ],
      "methods" : [
        "benchmarks/routing_benchmark.py::ASGIRunner.__init__",
        "benchmarks/routing_benchmark.py::ASGIRunner.run",
        "benchmarks/routing_benchmark.py::ASGIRunner.close"
      ]
    },
    {
      "anchor" : "starlette/_utils.py::AwaitableOrContextManager",
      "bases" : [

      ],
      "methods" : [

      ]
    },
    {
      "anchor" : "starlette/_utils.py::AwaitableOrContextManagerWrapper",
      "bases" : [

      ],
      "methods" : [
        "starlette/_utils.py::AwaitableOrContextManagerWrapper.__init__",
        "starlette/_utils.py::AwaitableOrContextManagerWrapper.__await__",
        "starlette/_utils.py::AwaitableOrContextManagerWrapper.__aenter__",
        "starlette/_utils.py::AwaitableOrContextManagerWrapper.__aexit__"
      ]
    },
    {
      "anchor" : "starlette/_utils.py::BaseExceptionGroup",
      "bases" : [

      ],
      "methods" : [

      ]
    },
    {
      "anchor" : "starlette/_utils.py::SupportsAsyncClose",
      "bases" : [

      ],
      "methods" : [
        "starlette/_utils.py::SupportsAsyncClose.close"
      ]
    },
    {
      "anchor" : "starlette/applications.py::Starlette",
      "bases" : [

      ],
      "methods" : [
        "starlette/applications.py::Starlette.__init__",
        "starlette/applications.py::Starlette.build_middleware_stack",
        "starlette/applications.py::Starlette.routes",
        "starlette/applications.py::Starlette.url_path_for",
        "starlette/applications.py::Starlette.__call__",
        "starlette/applications.py::Starlette.mount",
        "starlette/applications.py::Starlette.host",
        "starlette/applications.py::Starlette.add_middleware",
        "starlette/applications.py::Starlette.add_exception_handler",
        "starlette/applications.py::Starlette.add_route"
      ]
    },
    {
      "anchor" : "starlette/authentication.py::AuthCredentials",
      "bases" : [

      ],
      "methods" : [
        "starlette/authentication.py::AuthCredentials.__init__"
      ]
    },
    {
      "anchor" : "starlette/authentication.py::AuthenticationBackend",
      "bases" : [

      ],
      "methods" : [
        "starlette/authentication.py::AuthenticationBackend.authenticate"
      ]
    },
    {
      "anchor" : "starlette/authentication.py::AuthenticationError",
      "bases" : [

      ],
      "methods" : [

      ]
    },
    {
      "anchor" : "starlette/authentication.py::BaseUser",
      "bases" : [

      ],
      "methods" : [
        "starlette/authentication.py::BaseUser.is_authenticated",
        "starlette/authentication.py::BaseUser.display_name",
        "starlette/authentication.py::BaseUser.identity"
      ]
    },
    {
      "anchor" : "starlette/authentication.py::SimpleUser",
      "bases" : [

      ],
      "methods" : [
        "starlette/authentication.py::SimpleUser.__init__",
        "starlette/authentication.py::SimpleUser.is_authenticated",
        "starlette/authentication.py::SimpleUser.display_name"
      ]
    },
    {
      "anchor" : "starlette/authentication.py::UnauthenticatedUser",
      "bases" : [

      ],
      "methods" : [
        "starlette/authentication.py::UnauthenticatedUser.is_authenticated",
        "starlette/authentication.py::UnauthenticatedUser.display_name"
      ]
    },
    {
      "anchor" : "starlette/background.py::BackgroundTask",
      "bases" : [

      ],
      "methods" : [
        "starlette/background.py::BackgroundTask.__init__",
        "starlette/background.py::BackgroundTask.__call__"
      ]
    },
    {
      "anchor" : "starlette/background.py::BackgroundTasks",
      "bases" : [

      ],
      "methods" : [
        "starlette/background.py::BackgroundTasks.__init__",
        "starlette/background.py::BackgroundTasks.add_task",
        "starlette/background.py::BackgroundTasks.__call__"
      ]
    },
    {
      "anchor" : "starlette/concurrency.py::_StopIteration",
      "bases" : [

      ],
      "methods" : [

      ]
    },
    {
      "anchor" : "starlette/confi
"""#
}
